### ISSUE TITLE
[Bug] Extreme value not limited in the global number tag 

### ISSUE THREAD

**Issue by chinhan99** [AY2223S1-CS2113-W12-2/tp#145]
![image](https://user-images.githubusercontent.com/62207919/197999573-21fdfb32-109f-469d-82f4-c831075e9dd5.png)

Suggested to set a quantity limit as extreme values will overflow from Long or Int values and set an awkward error message.
Perhaps can take into reference with the way Add Command deals with extreme values.

**Comment by chydarren** [comment]
@paullowse has fixed this bug.
