### ISSUE TITLE
[Bug] Wrong stats display for different year/month.

### ISSUE THREAD

**Issue by chinhan99** [AY2223S1-CS2113-W12-2/tp#147]
![image](https://user-images.githubusercontent.com/62207919/198048844-e53f124d-62aa-4df2-9779-f36592d74e8e.png)

As seen in the screenshot, the transactions are done in 2022. But when given a stats command to list by year and month, it displayed the items in year 2022. 

Suggested to add more test cases too for assurance. 
1) Check for stats output for months that are not registered in transactions. There shouldnt be any output I suppose. 
2) Check for stats output for different months. Summaries from other months shouldnt show up at all.

**Comment by chydarren** [comment]
Thanks for finding this bug @chinhan99, and @paullowse for the attempt to fix the issue! To avoid duplicative code in the TransactionList class, I have updated the existing categoricalSavings-related functions to include the ArrayList instead, and modified the Stats command (list all categorical savings) to pass in the Transaction list, as per this PR: https://github.com/AY2223S1-CS2113-W12-2/tp/pull/150. 

Thank you!
