### ISSUE TITLE
[PE-D][Tester E] Invalid February dates are accepted

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-W12-2/tp#164]
![bug.png](https://raw.githubusercontent.com/naz019/ped/main/files/8793520f-1c61-499d-a565-92cf7a872790.png)

To reproduce: Use an add command that gives any date from 29022022 to 31022022.

This should give an 'invalid date' error but is instead entered as 2802022 for all cases.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: naz019/ped#3

**Comment by chydarren** [comment]
Thank you for producing this error, which our team may not have noticed when we were adding the dates as we assumed that the `LocalDate` object would cover invalid dates by default. This is a very good finding, and our team has rectified it as per this PR: https://github.com/AY2223S1-CS2113-W12-2/tp/pull/201 by @chinhan99.
