### ISSUE TITLE
[PE-D][Tester C] Spacing

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-W12-2/tp#166]
Random whitespace between the last y of the date. ddMMyyy y was typed.
![123.PNG](https://raw.githubusercontent.com/P0tatoChips/ped/main/files/d0e56cb9-4521-4839-84e8-5b63a8ee45dd.PNG)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: P0tatoChips/ped#1

**Comment by chydarren** [comment]
Thank you for bringing up this bug, very observant indeed! @chinhan99 has rectified this issue as per this PR: https://github.com/AY2223S1-CS2113-W12-2/tp/pull/157/files.
