### ISSUE TITLE
[PE-D][Tester E] For months which have 30 days e.g. April, entering a date using the 31st day of that month is accepted.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-W12-2/tp#167]
![bug.png](https://raw.githubusercontent.com/naz019/ped/main/files/a85ba8a8-7e0f-41d7-b188-86365fc37105.png)

To reproduce: Take any month which has only 30 days e.g. April and use the add command using the month's 31st day. Example: add t/income c/bonus a/9999999 d/31042022 i/54624624

An 'invalid date' error is expected but instead, the program accepts the date by correcting the date to the 30th day e.g. 30042022 when user keys in 31042022

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: naz019/ped#4

**Comment by chydarren** [comment]
Thank you for bringing this up! This issue has been resolved by @chinhan99 via PR: https://github.com/AY2223S1-CS2113-W12-2/tp/pull/201.
