### ISSUE TITLE
[PE-D][Tester C] Managed to change output of invalid command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-W12-2/tp#174]
![123.PNG](https://raw.githubusercontent.com/P0tatoChips/ped/main/files/45362fe5-9519-4d7b-928b-00f0c74410b1.PNG)
The above is the normal output for an invalid command. However, was able to alter the output and throw a warning.

![123.PNG](https://raw.githubusercontent.com/P0tatoChips/ped/main/files/a76c6ba6-b5b3-4665-8b7d-a35a79b33c87.PNG)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: P0tatoChips/ped#2

**Comment by wcwy** [comment]
The difference in output is due to the warning level set for different files. This issue has been fixed by @chinhan99 in #201.
