### ISSUE TITLE
[PE-D][Tester E] Users are unable to search their list by month without specifying the year

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-W12-2/tp#176]
![bug.png](https://raw.githubusercontent.com/naz019/ped/main/files/f2241756-3aaf-4e52-984e-9735b6b991b1.png)

If the user wants to view his transactions in a given month regardless of year, he is unable to do so using the current implementation of this app. Is there a good reason to restrict the user from doing so? What if a user wants to compare transactions in a given month by year?

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: naz019/ped#6

**Comment by chydarren** [comment]
Thank you very much for bringing this up!

We did not allow a month without a year as it does not seem like a valid functionality to list all of the same months from different years. Nonetheless, I recognize your concern of wanting to compare transactions in a given month for each year, which seems like a probable need for our users. We will take your suggestion into consideration.

**Comment by chydarren** [comment]
After consideration, we will not be adding this feature for now as the scope of users who will require to view a specific month for different years in a transaction list is small. In the meantime, if you wish to view the expenditure statistics, you may use the stats command which provides a similar functionality.

We may consider this suggestion again in future iterations.
