### ISSUE TITLE
[PE-D][Tester D] Can possibly let the user know if their budget exceeded with the change of budget amount.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-W12-2/tp#195]
![image.png](https://raw.githubusercontent.com/dhanish265/ped/main/files/53e7df15-5553-4471-b9f5-2f899cb44556.png)

According to the previous budget, the expenses for October are still within budget. However, once the budget is changed to 100, perhaps a message can be displayed to the user to inform them that the budget has been exceeded already.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: dhanish265/ped#11

**Comment by wcwy** [comment]
Indeed a great suggestion, users can be more aware of the effect of their budget changes with this suggestion implemented! That also aligns with our purpose of the application to help to users to better manage their financial situation too. This suggestion has now been implemented in #202.
