### ISSUE TITLE
[PE-D][Tester B] Adding valid input examples (maybe UG examples) to error messages (suggestion)

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-W12-2/tp#200]
Do consider adding maybe UG examples to relevant error messages. For example, `delete e/1` for the wrong delete format error, etc. This will be very helpful for the user especially for long commands like `add` and `edit`.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: OVReader/ped#9

**Comment by chinhan99** [comment]
As error message can be quite long especially for AddCommands or StatsCommmands if we were to suggest the proper formatting, we will explore editing the error message and refer them to the help command as an alternative.
