### ISSUE TITLE
Code review for @chydarren

### ISSUE THREAD

**Issue by dranov** [AY2223S1-CS2113-W12-2/tp#221]
# @chydarren

These `X-PERCENT` constants are a bit strange. While wanting to avoid magic numbers is understandable, maybe give them some more semantically informative names, e.g. `VERY_HIGH_SAVINGS_RATE`, `HIGH_SAVINGS_RATE`, etc. `static final int THREE = 3` is still a magic number :-)

https://github.com/AY2223S1-CS2113-W12-2/tp/blob/b53a3c2bc91adbdeaaf886db361511e8925b02f1/src/main/java/seedu/duke/data/TransactionList.java#L337-L352

Besides this, the code is overall well-commented and easy to read.

**Comment by chydarren** [comment]
Thank you very much @dranov! I'll work on your feedback and give them the semantically informative names.
