### ISSUE TITLE
[Bug] Command "stats s/categories" duplicates output when used multiple times

### ISSUE THREAD

**Issue by chinhan99** [AY2223S1-CS2113-W12-2/tp#76]
### This is an example of the bug that was observed
```sh

Hello! I'm Moo and I will help you to manage your finances.
Enter <help> if you need the list of commands.
____________________________________________________________
add t/expense c/food a/20 d/13092022 i/NIL
____________________________________________________________
I have added the following Expense transaction:
[-][food] $20 at Sep 13 2022 | Description: NIL
____________________________________________________________
add t/income c/salary a/2000 d/30092022 i/jan_salary
____________________________________________________________
I have added the following Income transaction:
[+][salary] $2000 at Sep 30 2022 | Description: jan_salary
____________________________________________________________
stats s/categories
____________________________________________________________
Here are the total savings for each category:
[food] $20
[salary] $2000

____________________________________________________________
stats s/categories
____________________________________________________________
Here are the total savings for each category:
[food] $40
[salary] $4000
[food] $20
[salary] $2000

____________________________________________________________
```

There are duplicated entries when  "stats s/categories" command is called more than once in the program.

**Comment by chydarren** [comment]
Thanks for creating this issue, yes I am aware of this bug due to the initiation of a new class instance each time the Stats command is called. @wcwy, kindly amend the parser and implement a constructor to pass in the CategoryList instance for usage throughout the program. Thanks!

**Comment by chinhan99** [comment]
Noted ! @chydarren 
Thanks for the assist ! @wcwy

**Comment by chydarren** [comment]
As @wcwy had to focus on the refactoring of parser portion yesterday, I have fixed the severe bug this morning. Basically, the issue lies in the categories list not being cleared each time the instance is re-called, so it builds on its existing list. The fix to this is to clear the list after the temporary usage each time. Refer to this PR: https://github.com/AY2223S1-CS2113-W12-2/tp/pull/82.
